import type { Dispatch, SetStateAction } from "react";

import type { McpToolEditor } from "./AgentDefinitionEditor";
import type { RuntimeAgentDefinitionDraft, RuntimeModelSelection, RuntimeWorkspaceBinding, RuntimeWorkspaceMount } from "./lib/gateway";

type Setter<T> = Dispatch<SetStateAction<T>>;

export function StringRows({ label, values, set }: { label: string; values: string[]; set: Setter<string[]> }) {
  return <fieldset><legend>{label}</legend>{values.map((value, index) => <div key={index} className="definition-row"><input aria-label={`${label} ${index + 1}`} value={value} onChange={(event) => set((current) => replace(current, index, event.target.value))} /><Remove label={`${label} ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></div>)}<Add label={`Add ${label}`} onClick={() => set((current) => [...current, ""])} /></fieldset>;
}

export function PairRows({ label, left, right, values, set }: { label: string; left: string; right: string; values: string[][]; set(values: string[][]): void }) {
  return <fieldset><legend>{label}</legend>{values.map((value, index) => <div key={index} className="definition-row"><input aria-label={`${left} ${index + 1}`} value={value[0]} onChange={(event) => set(replace(values, index, [event.target.value, value[1]]))} /><input aria-label={`${right} ${index + 1}`} value={value[1]} onChange={(event) => set(replace(values, index, [value[0], event.target.value]))} /><Remove label={`${label} ${index + 1}`} onClick={() => set(remove(values, index))} /></div>)}<Add label={`Add ${label}`} onClick={() => set([...values, ["", ""]])} /></fieldset>;
}

export function ModelRows({ label, values, set }: { label: string; values: RuntimeModelSelection[]; set: Setter<RuntimeModelSelection[]> }) {
  return <fieldset><legend>{label}</legend>{values.map((value, index) => <div key={index} className="definition-row"><input aria-label={`${label} provider ${index + 1}`} value={value.provider_id} onChange={(event) => set((current) => replace(current, index, { ...value, provider_id: event.target.value }))} /><input aria-label={`${label} model ${index + 1}`} value={value.model_id} onChange={(event) => set((current) => replace(current, index, { ...value, model_id: event.target.value }))} /><Remove label={`${label} ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></div>)}<Add label={`Add ${label}`} onClick={() => set((current) => [...current, { provider_id: "", model_id: "" }])} /></fieldset>;
}

export function McpRows({ values, set }: { values: McpToolEditor[]; set: Setter<McpToolEditor[]> }) {
  return <fieldset><legend>MCP servers</legend>{values.map((tool, index) => <details key={index}><summary>MCP {index + 1} · {tool.name || "unnamed"}</summary><div className="definition-grid"><Field name={`MCP name ${index + 1}`} value={tool.name} set={(name) => update(set, index, { ...tool, name })} /><Field name={`MCP execution environment ${index + 1}`} value={tool.executionEnvironment} set={(executionEnvironment) => update(set, index, { ...tool, executionEnvironment })} /><label>Workspace access<select aria-label={`MCP workspace access ${index + 1}`} value={tool.workspaceAccess} onChange={(event) => update(set, index, { ...tool, workspaceAccess: event.target.value as "read" | "write" })}><option value="read">read</option><option value="write">write</option></select></label><Field name={`MCP command ${index + 1}`} value={tool.command} set={(command) => update(set, index, { ...tool, command })} /></div><StringRows label={`MCP arguments ${index + 1}`} values={tool.args} set={(next) => update(set, index, { ...tool, args: resolve(next, tool.args) })} /><fieldset><legend>Secret references</legend>{tool.environment.map((entry, entryIndex) => <div key={entryIndex} className="definition-row"><input aria-label={`MCP variable ${index + 1}.${entryIndex + 1}`} value={entry.variable} onChange={(event) => updateMcpEnvironment(set, values, index, entryIndex, { ...entry, variable: event.target.value })} /><select aria-label={`MCP secret source ${index + 1}.${entryIndex + 1}`} value={entry.source} onChange={(event) => updateMcpEnvironment(set, values, index, entryIndex, { ...entry, source: event.target.value as "environment" | "file" })}><option value="environment">environment</option><option value="file">file</option></select><input aria-label={`MCP secret reference ${index + 1}.${entryIndex + 1}`} value={entry.reference} onChange={(event) => updateMcpEnvironment(set, values, index, entryIndex, { ...entry, reference: event.target.value })} /><Remove label={`MCP secret reference ${index + 1}.${entryIndex + 1}`} onClick={() => update(set, index, { ...tool, environment: remove(tool.environment, entryIndex) })} /></div>)}<Add label={`Add MCP secret reference ${index + 1}`} onClick={() => update(set, index, { ...tool, environment: [...tool.environment, { variable: "", source: "environment" as const, reference: "" }] })} /></fieldset><Remove label={`MCP server ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></details>)}<Add label="Add MCP server" onClick={() => set((current) => [...current, { name: "", executionEnvironment: "", workspaceAccess: "read", command: "", args: [], environment: [] }])} /></fieldset>;
}

export function CommandRows({ values, set }: { values: RuntimeAgentDefinitionDraft["ui_commands"]; set: Setter<RuntimeAgentDefinitionDraft["ui_commands"]> }) {
  return <fieldset><legend>UI commands</legend>{values.map((item, index) => <details key={index}><summary>Command {index + 1} · {item.id || "unnamed"}</summary><div className="definition-grid">{(["id", "name", "usage", "description", "hint", "prompt"] as const).map((field) => <Field key={field} name={`Command ${field} ${index + 1}`} value={item[field]} set={(value) => update(set, index, { ...item, [field]: value })} />)}</div><Remove label={`UI command ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></details>)}<Add label="Add UI command" onClick={() => set((current) => [...current, { id: "", name: "", usage: "", description: "", hint: "", prompt: "" }])} /></fieldset>;
}

export function HookRows({ values, set }: { values: RuntimeAgentDefinitionDraft["hooks"]; set: Setter<RuntimeAgentDefinitionDraft["hooks"]> }) {
  return <fieldset><legend>Hooks</legend>{values.map((item, index) => <div key={index} className="definition-row"><input aria-label={`Hook name ${index + 1}`} value={item.name} onChange={(event) => update(set, index, { ...item, name: event.target.value })} /><select aria-label={`Hook phase ${index + 1}`} value={item.phase} onChange={(event) => update(set, index, { ...item, phase: event.target.value as typeof item.phase })}><option value="before_tool">before tool</option><option value="after_tool">after tool</option><option value="before_turn">before turn</option><option value="after_turn">after turn</option></select><input aria-label={`Hook command ${index + 1}`} value={item.command} onChange={(event) => update(set, index, { ...item, command: event.target.value })} /><input aria-label={`Hook timeout ${index + 1}`} type="number" min="1" max="300" value={item.timeout_secs} onChange={(event) => update(set, index, { ...item, timeout_secs: Number(event.target.value) })} /><label><input type="checkbox" checked={item.blocking} onChange={(event) => update(set, index, { ...item, blocking: event.target.checked })} /> blocking</label><Remove label={`Hook ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></div>)}<Add label="Add hook" onClick={() => set((current) => [...current, { name: "", phase: "after_tool", command: "", timeout_secs: 30, blocking: false }])} /></fieldset>;
}

export function PresentationRows({ values, set }: { values: RuntimeAgentDefinitionDraft["tool_presentations"]; set: Setter<RuntimeAgentDefinitionDraft["tool_presentations"]> }) {
  return <fieldset><legend>Tool presentations</legend>{values.map((item, index) => <div key={index} className="definition-row"><input aria-label={`Presentation tool ${index + 1}`} value={item.tool_name} onChange={(event) => update(set, index, { ...item, tool_name: event.target.value })} /><input aria-label={`Presentation label ${index + 1}`} value={item.label} onChange={(event) => update(set, index, { ...item, label: event.target.value })} /><select aria-label={`Presentation kind ${index + 1}`} value={item.kind} onChange={(event) => update(set, index, { ...item, kind: event.target.value as typeof item.kind })}>{["generic", "command", "file", "search", "resource"].map((kind) => <option key={kind}>{kind}</option>)}</select><input aria-label={`Presentation target ${index + 1}`} value={item.target_field ?? ""} onChange={(event) => update(set, index, { ...item, target_field: event.target.value || undefined })} /><Remove label={`Tool presentation ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></div>)}<Add label="Add tool presentation" onClick={() => set((current) => [...current, { tool_name: "", label: "", kind: "generic" }])} /></fieldset>;
}

export function WorkspaceBinding({ value, set }: { value?: RuntimeWorkspaceBinding; set: Setter<RuntimeWorkspaceBinding | undefined> }) {
  if (!value) return <button type="button" className="secondary-button" onClick={() => set({ execution_target: "", path: "", read_only: false })}>Configure Agent workspace</button>;
  return <fieldset><legend>Agent workspace</legend><div className="definition-row"><input aria-label="Agent workspace execution target" value={value.execution_target} onChange={(event) => set({ ...value, execution_target: event.target.value })} /><input aria-label="Agent workspace path" value={value.path} onChange={(event) => set({ ...value, path: event.target.value })} /><input aria-label="Agent workspace instruction focus" value={value.instruction_focus ?? ""} onChange={(event) => set({ ...value, instruction_focus: event.target.value || undefined })} /><label><input type="checkbox" checked={value.read_only} onChange={(event) => set({ ...value, read_only: event.target.checked })} /> read only</label><Remove label="Agent workspace" onClick={() => set(undefined)} /></div></fieldset>;
}

export function MountRows({ values, set }: { values: RuntimeWorkspaceMount[]; set: Setter<RuntimeWorkspaceMount[]> }) {
  return <fieldset><legend>Workspace mounts</legend>{values.map((mount, index) => <details key={index}><summary>Mount {index + 1} · {mount.reference || "unnamed"}</summary><div className="definition-grid"><Field name={`Mount reference ${index + 1}`} value={mount.reference} set={(reference) => update(set, index, { ...mount, reference })} /><label>Role<select aria-label={`Mount role ${index + 1}`} value={mount.role} onChange={(event) => update(set, index, { ...mount, role: event.target.value as typeof mount.role })}>{["agent_home", "task", "dependency", "artifact"].map((role) => <option key={role}>{role}</option>)}</select></label><Field name={`Mount execution target ${index + 1}`} value={mount.binding.execution_target} set={(execution_target) => update(set, index, { ...mount, binding: { ...mount.binding, execution_target } })} /><Field name={`Mount path ${index + 1}`} value={mount.binding.path} set={(path) => update(set, index, { ...mount, binding: { ...mount.binding, path } })} /><Field name={`Mount instruction focus ${index + 1}`} value={mount.binding.instruction_focus ?? ""} set={(instruction_focus) => update(set, index, { ...mount, binding: { ...mount.binding, instruction_focus: instruction_focus || undefined } })} /></div><div className="definition-row"><Toggle label={`Mount read only ${index + 1}`} value={mount.binding.read_only} set={(read_only) => update(set, index, { ...mount, binding: { ...mount.binding, read_only } })} /><Toggle label={`Mount read ${index + 1}`} value={mount.capabilities.read} set={(read) => update(set, index, { ...mount, capabilities: { ...mount.capabilities, read } })} /><Toggle label={`Mount write ${index + 1}`} value={mount.capabilities.write} set={(write) => update(set, index, { ...mount, capabilities: { ...mount.capabilities, write } })} /><Toggle label={`Mount command ${index + 1}`} value={mount.capabilities.command} set={(command) => update(set, index, { ...mount, capabilities: { ...mount.capabilities, command } })} /><Toggle label={`Mount git ${index + 1}`} value={mount.capabilities.git} set={(git) => update(set, index, { ...mount, capabilities: { ...mount.capabilities, git } })} /></div><Remove label={`Workspace mount ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></details>)}<Add label="Add workspace mount" onClick={() => set((current) => [...current, { reference: "", role: "dependency", binding: { execution_target: "", path: "", read_only: true }, capabilities: { read: true, write: false, command: false, git: false } }])} /></fieldset>;
}

export function PromptProfileRows({ values, set }: { values: RuntimeAgentDefinitionDraft["prompt_profiles"]; set: Setter<RuntimeAgentDefinitionDraft["prompt_profiles"]> }) {
  return <fieldset><legend>Prompt profiles</legend>{values.map((profile, index) => <details key={index}><summary>Profile {index + 1} · {profile.id || "unnamed"}</summary><Field name={`Prompt profile id ${index + 1}`} value={profile.id} set={(id) => update(set, index, { ...profile, id })} /><label>Write-only system prompt<textarea aria-label={`Prompt profile system prompt ${index + 1}`} value={profile.system_prompt} onChange={(event) => update(set, index, { ...profile, system_prompt: event.target.value })} /></label><ModelRows label={`Prompt profile models ${index + 1}`} values={profile.qualified_models} set={(next) => update(set, index, { ...profile, qualified_models: resolve(next, profile.qualified_models) })} /><Remove label={`Prompt profile ${index + 1}`} onClick={() => set((current) => remove(current, index))} /></details>)}<Add label="Add prompt profile" onClick={() => set((current) => [...current, { id: "", qualified_models: [], system_prompt: "" }])} /></fieldset>;
}

function Field({ name, value, set }: { name: string; value: string; set(value: string): void }) { return <label>{name}<input aria-label={name} value={value} onChange={(event) => set(event.target.value)} /></label>; }
function Toggle({ label, value, set }: { label: string; value: boolean; set(value: boolean): void }) { return <label><input aria-label={label} type="checkbox" checked={value} onChange={(event) => set(event.target.checked)} /> {label}</label>; }
function Add({ label, onClick }: { label: string; onClick(): void }) { return <button type="button" className="secondary-button" onClick={onClick}>{label}</button>; }
function Remove({ label, onClick }: { label: string; onClick(): void }) { return <button type="button" className="secondary-button" aria-label={`Remove ${label}`} onClick={onClick}>Remove</button>; }
function replace<T>(values: T[], index: number, value: T) { return values.map((item, itemIndex) => itemIndex === index ? value : item); }
function remove<T>(values: T[], index: number) { return values.filter((_, itemIndex) => itemIndex !== index); }
function update<T>(set: Setter<T[]>, index: number, value: T) { set((current) => replace(current, index, value)); }
function resolve<T>(next: SetStateAction<T[]>, current: T[]) { return typeof next === "function" ? next(current) : next; }
function updateMcpEnvironment(set: Setter<McpToolEditor[]>, values: McpToolEditor[], toolIndex: number, entryIndex: number, entry: McpToolEditor["environment"][number]) { const tool = values[toolIndex]; update(set, toolIndex, { ...tool, environment: replace(tool.environment, entryIndex, entry) }); }
