//! Message types — request input (`MessageParam`) and response output (`Message`).

use serde::{Deserialize, Serialize};

use super::block::{ContentBlock, ThinkingBlock, UserContent};
use super::stop_reason::StopReason;
use super::usage::Usage;
use serde_json::Value as JsonValue;

/// Input message parameter — what callers send in the `messages` array.
///
/// Construct with [`MessageParam::user`] / [`MessageParam::assistant`] / etc.
/// The `content` field accepts either a plain string (shorthand) or
/// structured blocks.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MessageParam {
    /// Role: `"user"` or `"assistant"`.
    pub role: MessageRole,
    /// Message content.
    pub content: UserContent,
}

impl MessageParam {
    /// Create a user message with a single string content.
    #[must_use]
    pub fn user(text: impl Into<String>) -> Self {
        Self {
            role: MessageRole::User,
            content: UserContent::String(text.into()),
        }
    }

    /// Create a user message with structured content blocks.
    #[must_use]
    pub fn user_blocks(blocks: Vec<super::block::UserContentBlock>) -> Self {
        Self {
            role: MessageRole::User,
            content: UserContent::Blocks(blocks),
        }
    }

    /// Create an assistant message with structured content blocks.
    /// Used when re-feeding an assistant turn back into the API.
    #[must_use]
    pub fn assistant_blocks(blocks: Vec<ContentBlock>) -> Self {
        // Note: in request messages, assistant content is typically sent as
        // raw JSON arrays. We reuse the same shape — caller is responsible
        // for ensuring blocks are valid for re-feed.
        Self {
            role: MessageRole::Assistant,
            content: UserContent::Blocks(
                blocks
                    .into_iter()
                    .map(assistant_block_to_user_block)
                    .collect(),
            ),
        }
    }
}

/// Message role discriminator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MessageRole {
    /// User turn.
    User,
    /// Assistant turn.
    Assistant,
}

/// Convert a [`ContentBlock`] (assistant-side) into a [`UserContentBlock`]
/// suitable for inclusion in a request message. This is used when
/// re-feeding a prior assistant turn back into the API.
///
/// Note: assistant content blocks in *request* messages are typically
/// passed as raw JSON, not strongly-typed. v2 keeps the strict typing for
/// input clarity but the conversion may need to relax for full protocol
/// compatibility in edge cases.
fn assistant_block_to_user_block(block: ContentBlock) -> super::block::UserContentBlock {
    match block {
        ContentBlock::Text(t) => super::block::UserContentBlock::Text(t),
        ContentBlock::Thinking(ThinkingBlock {
            thinking,
            signature,
            ..
        }) => {
            // Thinking blocks in re-fed assistant turns are passed as opaque
            // JSON; the protocol SDK preserves them through the loop.
            super::block::UserContentBlock::Other(serde_json::json!({
                "type": "thinking",
                "thinking": thinking,
                "signature": signature,
            }))
        }
        ContentBlock::ToolUse(tu) => super::block::UserContentBlock::Other(serde_json::json!({
            "type": "tool_use",
            "id": tu.id,
            "name": tu.name,
            "input": tu.input,
        })),
    }
}

/// Output message — the model's response.
///
/// Returned by `POST /v1/messages` (sync) and assembled incrementally by
/// [`crate::api::message_stream::MessageStream::final_message`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Message {
    /// Unique message identifier (`msg_xxx`).
    pub id: String,
    /// Always `"message"`.
    #[serde(rename = "type")]
    pub kind: MessageKind,
    /// Always `"assistant"`.
    pub role: MessageRole,
    /// Content blocks generated by the model.
    pub content: Vec<ContentBlock>,
    /// Model that produced this response.
    pub model: String,
    /// Why the model stopped generating.
    pub stop_reason: Option<StopReason>,
    /// Which custom stop sequence was generated, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_sequence: Option<String>,
    /// Token usage.
    pub usage: Usage,
}

impl Message {
    /// Concatenate all text blocks into a single string. Useful for simple
    /// "just print the response" use cases.
    #[must_use]
    pub fn text(&self) -> String {
        self.content
            .iter()
            .filter_map(ContentBlock::text)
            .collect::<Vec<_>>()
            .join("")
    }

    /// Find the first `tool_use` block, if any.
    #[must_use]
    pub fn first_tool_use(&self) -> Option<&super::block::ToolUseBlock> {
        self.content.iter().find_map(|b| match b {
            ContentBlock::ToolUse(tu) => Some(tu),
            _ => None,
        })
    }

    /// All `tool_use` blocks in this message.
    pub fn tool_uses(&self) -> impl Iterator<Item = &super::block::ToolUseBlock> {
        self.content.iter().filter_map(|b| match b {
            ContentBlock::ToolUse(tu) => Some(tu),
            _ => None,
        })
    }
}

/// Discriminator for [`Message`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MessageKind {
    /// Message object.
    #[serde(rename = "message")]
    Message,
}

/// Token count returned by `POST /v1/messages/count_tokens`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MessageTokensCount {
    /// Total input tokens across the messages, system prompt, and tools.
    pub input_tokens: u32,
    /// Some fields are kept opaque in case the API adds more.
    #[serde(flatten)]
    pub extra: JsonValue,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::types::block::TextBlock;
    use serde_json::json;

    #[test]
    fn user_message_string_round_trip() {
        let m = MessageParam::user("Hello");
        let json = serde_json::to_string(&m).unwrap();
        assert_eq!(json, r#"{"role":"user","content":"Hello"}"#);
        let back: MessageParam = serde_json::from_str(&json).unwrap();
        assert_eq!(back, m);
    }

    #[test]
    fn user_message_blocks_round_trip() {
        let m = MessageParam::user_blocks(vec![crate::api::types::UserContentBlock::text(
            "multi\nline",
        )]);
        let json = serde_json::to_string(&m).unwrap();
        let back: MessageParam = serde_json::from_str(&json).unwrap();
        assert_eq!(back, m);
    }

    #[test]
    fn message_response_round_trip() {
        let m = Message {
            id: "msg_abc".to_string(),
            kind: MessageKind::Message,
            role: MessageRole::Assistant,
            content: vec![ContentBlock::Text(TextBlock::new("Hello!"))],
            model: "claude-sonnet-5-20260601".to_string(),
            stop_reason: Some(StopReason::EndTurn),
            stop_sequence: None,
            usage: Usage {
                input_tokens: 10,
                output_tokens: 5,
                cache_creation_input_tokens: None,
                cache_read_input_tokens: None,
            },
        };
        let json = serde_json::to_string(&m).unwrap();
        let back: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(back, m);
    }

    #[test]
    fn message_text_concat() {
        let m = Message {
            id: "msg_x".to_string(),
            kind: MessageKind::Message,
            role: MessageRole::Assistant,
            content: vec![
                ContentBlock::Text(TextBlock::new("Hello, ")),
                ContentBlock::Text(TextBlock::new("world!")),
            ],
            model: "claude-sonnet-5-20260601".to_string(),
            stop_reason: Some(StopReason::EndTurn),
            stop_sequence: None,
            usage: Usage {
                input_tokens: 0,
                output_tokens: 5,
                cache_creation_input_tokens: None,
                cache_read_input_tokens: None,
            },
        };
        assert_eq!(m.text(), "Hello, world!");
    }

    #[test]
    fn tokens_count_round_trip() {
        let tc = MessageTokensCount {
            input_tokens: 42,
            extra: json!({}),
        };
        let json = serde_json::to_string(&tc).unwrap();
        assert_eq!(json, r#"{"input_tokens":42}"#);
        let back: MessageTokensCount = serde_json::from_str(&json).unwrap();
        assert_eq!(back.input_tokens, 42);
    }
}
